services:
  mongo:
    container_name: "Mongo"
    image: mongo:4.4.6
    volumes:
      - ./storage/data/db:/data/db
    ports:
      - 27017:27017
    networks:
      - kenility-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: backend.Dockerfile
      args:
        APP_VERSION: ${APP_VERSION:-dev}
    container_name: "Kenility-API"
    depends_on:
      - mongo
    volumes:
      - ./storage/uploads:/app/dist/assets
    ports:
      - 3000:3000
    networks:
      - kenility-net
    environment:
      MONGO_URI: mongodb://admin:admin@mongo:27017
      MONGO_USER: admin
      MONGO_PASS: admin
      MONGO_DATABASE: kenility
      JWT_SECRET: 3cbe8eb706f7a93feac8ff218282a60eace285a4363ee40cfbaf9cfa2d3aa5a2
      JWT_EXPIRES: 24h
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
      args:
        APP_VERSION: ${APP_VERSION:-dev}
    container_name: "Kenility-Frontend"
    depends_on:
      - mongo
      - api
    ports:
      - 8080:80
    networks:
      - kenility-net
    restart: unless-stopped

networks:
  kenility-net:
    driver: bridge
